# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69b44d99c60c18dffb00aae0fa2d24ba768c37ab47f4bda94afdc8ba36f28083eef582e95392766077c9b3982c93ffbe211baa9ead6b46186703310c25859e47

test:
  secret_key_base: 91fa525ca8f2452771673e8b5ff1b6b93527392505f226c7dbba6e3efca70ceefc3027f54db9e7401f05ee043cf88575284e244707c8976ef3ac86a3d6b9d07b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
